/// Flutter icons Exampal
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Exampal
///      fonts:
///       - asset: fonts/Exampal.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Exampal {
  Exampal._();

  static const _kFontFam = 'Exampal';
  static const _kFontPkg = null;

  static const IconData add_chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
